export const componentDocumentation = {
  buttons: {
    title: "Button",
    description: "Кнопка запускает действие или оформляет переход в едином стиле Mecorion.",
    types: ["Варианты: default, primary, ghost, outline, danger, success и warning.", "Размеры: sm, md и lg.", "Состояния: loading и disabled; формы icon, rounded и link."],
    usage: '<UiButton variant="primary" size="md" @click="save">Сохранить</UiButton>',
  },
  inputs: {
    title: "Input",
    description: "Однострочное поле для ввода текста, поиска, email, пароля и других значений формы.",
    types: ["Размеры: sm, md и lg.", "Состояния: default, success, error, disabled и readonly.", "Слоты prefix и suffix добавляют произвольный контент по краям."],
    usage: '<UiInput v-model="name" label="Название" placeholder="Введите название" />',
  },
  avatar: {
    title: "Avatar",
    description: "Показывает изображение пользователя или текстовый fallback, а также его статус.",
    types: ["Размеры: sm, default и lg.", "Состояния статуса: online, busy и offline.", "Поддерживает fallback, badge, группы и интерактивный режим."],
    usage: '<UiAvatar src="/avatar.jpg" alt="Иван" fallback="ИИ" status="online" />',
  },
  breadcrumb: {
    title: "Breadcrumb",
    description: "Показывает положение текущей страницы в иерархии и предоставляет переходы к родителям.",
    types: ["Обычная цепочка и цепочка с ограничением maxItems.", "Пункты могут быть ссылками, текущей страницей или выпадающим меню.", "Поддерживает пользовательский разделитель."],
    usage: '<UiBreadcrumb :items="[{label: \'Главная\', to: \'/\'}, {label: \'Профиль\'}]" />',
  },
  empty: {
    title: "Empty State",
    description: "Сообщает об отсутствии данных и предлагает понятное следующее действие.",
    types: ["Варианты: default и outline.", "Размеры: sm, default и large.", "Слоты media, title, description, actions и footer."],
    usage: '<UiEmptyState title="Пока пусто" description="Создайте первый элемент."><template #actions><UiButton>Создать</UiButton></template></UiEmptyState>',
  },
  skeleton: {
    title: "Skeleton",
    description: "Показывает структуру будущего контента во время загрузки данных.",
    types: ["Формы: text, circle и прямоугольная поверхность.", "Размер задаётся через width и height.", "Несколько элементов объединяются в макет карточки или списка."],
    usage: '<UiSkeleton width="100%" height="120px" />',
  },
  item: {
    title: "Item",
    description: "Универсальная строка списка для настроек, команд, файлов и навигационных сущностей.",
    types: ["Размеры: sm и default.", "Поддерживает media, title, description, meta и actions.", "Используется отдельно или внутри UiItemGroup с разделителями."],
    usage: '<UiItem title="Профиль" description="Настройки аккаунта"><template #action><UiButton size="sm">Открыть</UiButton></template></UiItem>',
  },
  drawer: {
    title: "Drawer",
    description: "Выводит дополнительный интерфейс в панели, появляющейся от края экрана.",
    types: ["Положения: left, right, top и bottom.", "Состояния: открытый, закрывающийся и modal.", "Поддерживает заголовок, описание, footer и кнопку закрытия."],
    usage: '<UiDrawer v-model:open="open" title="Настройки"><p>Содержимое панели</p></UiDrawer>',
  },
  dialog: {
    title: "Dialog",
    description: "Модальное окно для подтверждений, форм и сфокусированных пользовательских сценариев.",
    types: ["Размеры: sm, default и lg.", "Состояния: open, modal и без кнопки закрытия.", "Слоты header, default и footer."],
    usage: '<UiDialog v-model:open="open" title="Удалить запись?">Подтвердите действие.</UiDialog>',
  },
  popover: {
    title: "Popover",
    description: "Показывает небольшой контекстный блок рядом с управляющим элементом.",
    types: ["Позиционируется относительно trigger и адаптируется к viewport.", "Поддерживает управляемое открытие и закрытие по внешнему клику.", "Содержимое может включать текст, формы и действия."],
    usage: '<UiPopover><template #trigger><UiButton>Открыть</UiButton></template>Контент</UiPopover>',
  },
  "dropdown-menu": {
    title: "Dropdown Menu",
    description: "Контекстное меню команд с клавиатурной навигацией и вложенными пунктами.",
    types: ["Пункты: action, label, separator, checkbox, radio и submenu.", "Состояния: disabled, checked и danger.", "Поддерживает иконки и клавиатурные сокращения."],
    usage: '<UiDropdownMenu :items="items"><template #trigger><UiButton>Команды</UiButton></template></UiDropdownMenu>',
  },
  tooltip: {
    title: "Tooltip",
    description: "Показывает короткую подсказку при наведении или фокусе на элементе.",
    types: ["Положения: top, right, bottom и left.", "Поддерживает задержку появления и произвольный trigger.", "Не заменяет важные постоянно видимые подписи."],
    usage: '<UiTooltip content="Открыть настройки"><UiButton icon><SvgIcon name="settings" /></UiButton></UiTooltip>',
  },
  field: {
    title: "Field",
    description: "Структурирует подпись, контрол, описание и сообщение валидации поля формы.",
    types: ["Композиции: вертикальная, горизонтальная и responsive.", "Состояния: default, invalid и disabled.", "Связанные поля объединяются через FieldGroup и Fieldset."],
    usage: '<UiField label="Email" description="Рабочая почта"><UiInput v-model="email" /></UiField>',
  },
  form: {
    title: "Form",
    description: "Контейнер формы с общей обработкой submit, состоянием загрузки и группировкой полей.",
    types: ["Интервалы: compact, default и comfortable.", "Состояния: loading и disabled через вложенные fieldset.", "Слоты default и actions формируют содержимое и действия."],
    usage: '<UiForm @submit="submit"><UiInput v-model="name" label="Имя" /><template #actions><UiButton type="submit">Сохранить</UiButton></template></UiForm>',
  },
  "file-picker": {
    title: "File Picker",
    description: "Выбирает файлы с устройства, проверяет ограничения и показывает выбранные элементы.",
    types: ["Варианты: dropzone и button.", "Режимы: single и multiple.", "Состояния: dragging, invalid, disabled; ограничения accept, maxSize и maxFiles."],
    usage: '<UiFilePicker v-model="files" multiple accept="image/*" :max-size="5242880" />',
  },
  textarea: {
    title: "Textarea",
    description: "Многострочное поле для описаний, комментариев и длинного пользовательского текста.",
    types: ["Состояния: default, success, danger, disabled и readonly.", "Поддерживает hint и стандартные HTML-атрибуты.", "Высоту можно ограничивать через rows и CSS."],
    usage: '<UiTextarea v-model="description" label="Описание" :rows="5" />',
  },
  select: {
    title: "Select",
    description: "Кастомный список выбора с управлением клавиатурой и адаптивным позиционированием меню.",
    types: ["Размеры: default и sm.", "Состояния: default, open, invalid, disabled и scrollable.", "Опции поддерживают label, value и disabled."],
    usage: '<UiSelect v-model="service" label="Сервис" :options="options" size="sm" />',
  },
  checkbox: {
    title: "Checkbox",
    description: "Управляет независимым логическим выбором или выбором нескольких элементов.",
    types: ["Размеры: default и sm.", "Состояния: checked, unchecked, indeterminate, invalid и disabled.", "Поддерживает label и description."],
    usage: '<UiCheckbox v-model="accepted" label="Принять условия" />',
  },
  radio: {
    title: "Radio Group",
    description: "Позволяет выбрать ровно один вариант из связанной группы значений.",
    types: ["Варианты отображения: default и cards.", "Ориентации: vertical и horizontal.", "Состояния: selected, invalid, disabled."],
    usage: '<UiRadioGroup v-model="plan" label="Тариф" :options="plans" />',
  },
  toggle: {
    title: "Toggle",
    description: "Мгновенно включает или выключает режим, фильтр или форматирование.",
    types: ["Варианты: default и outline.", "Размеры: sm и default.", "Состояния: on, off и disabled."],
    usage: '<UiToggle v-model="favorite" aria-label="Добавить в избранное"><SvgIcon name="star" /></UiToggle>',
  },
  slider: {
    title: "Slider",
    description: "Выбирает числовое значение или диапазон на непрерывной шкале.",
    types: ["Одиночное значение, диапазон и несколько точек.", "Ориентации: horizontal и vertical.", "Состояния: default и disabled; настраиваются min, max и step."],
    usage: '<UiSlider v-model="volume" :min="0" :max="100" :step="1" label="Громкость" />',
  },
  progress: {
    title: "Progress",
    description: "Отображает степень выполнения операции или прохождения процесса.",
    types: ["Размеры: sm, default и lg.", "Может показывать label и числовое значение.", "Поддерживает min, max и пользовательское форматирование."],
    usage: '<UiProgress :value="progress" label="Загрузка" show-value size="sm" />',
  },
  spinner: {
    title: "Spinner",
    description: "Показывает неопределённую загрузку, когда точный прогресс неизвестен.",
    types: ["Размеры: xs, sm, default и lg.", "Может иметь доступную текстовую метку или быть decorative.", "Используется самостоятельно и внутри кнопок, badge и полей."],
    usage: '<UiSpinner size="sm" label="Загрузка данных" />',
  },
  cards: {
    title: "Card",
    description: "Группирует связанные данные и действия на самостоятельной поверхности.",
    types: ["Варианты: default, flat и raised.", "Размеры: default и sm; состояния interactive и static.", "Слоты media, header, action, default и footer."],
    usage: '<UiCard title="Проект" description="Описание проекта"><p>Контент</p><template #footer><UiButton>Открыть</UiButton></template></UiCard>',
  },
  alerts: {
    title: "Alert",
    description: "Сообщает о результате операции, предупреждении или важном изменении состояния.",
    types: ["Варианты: default, success, warning и danger.", "Поддерживает отображение с иконкой и без неё.", "Действие размещается справа или под описанием."],
    usage: '<UiAlert variant="success" title="Готово">Изменения сохранены.</UiAlert>',
  },
  badges: {
    title: "Badge",
    description: "Компактно обозначает статус, категорию, количество или короткую метку.",
    types: ["Варианты: default, soft, success, warning и danger.", "Состояния: static, link, loading и disabled.", "Badge-ссылка автоматически показывает внешнюю стрелку."],
    usage: '<UiBadge variant="success">Активен</UiBadge>',
  },
  icons: {
    title: "Icon",
    description: "Выводит локальные SVG-символы из спрайта Mecorion через единый компонент.",
    types: ["Имя соответствует пути файла внутри assets/icons.", "Иконка может быть декоративной или иметь доступный title.", "Размер и цвет наследуются из CSS контекста."],
    usage: '<SvgIcon name="settings" title="Настройки" />',
  },
  typography: {
    title: "Typography",
    description: "Определяет иерархию заголовков, основного текста, подписей и метаданных.",
    types: ["Заголовки: display, title-1, title-2 и title-3.", "Текст: lg, default и sm.", "Caption применяется для коротких служебных подписей."],
    usage: '<h2 class="mc-title-2">Заголовок</h2>\n<p class="mc-text">Основной текст.</p>',
  },
};
