<script setup lang="ts">
import UiButton from "@mecorion-ui/UiButton.vue";
import UiCard from "@mecorion-ui/UiCard.vue";
import UiDialog from "@mecorion-ui/UiDialog.vue";
import UiEmptyState from "@mecorion-ui/UiEmptyState.vue";
import UiForm from "@mecorion-ui/UiForm.vue";
import UiInput from "@mecorion-ui/UiInput.vue";
import UiSelect from "@mecorion-ui/UiSelect.vue";
import UiTextarea from "@mecorion-ui/UiTextarea.vue";

definePageMeta({title: "Правовые статусы"});
type RefItem = {code: string; name: string};
type EntityRef = {id: string; name: string; type?: string};
type LegalStatus = {id: string; resourceId: string; resourceName: string; resourceType: string; status: string; statusName: string; territory: string; sourceType: string; validFromDtm: string; validUntilDtm: string | null; revokeDtm: string | null};
type License = {id: string; resourceName: string; typeName: string; rightsHolder: string | null; licenseReference: string | null; territories: string[]; validUntilDt: string | null; revokeDtm: string | null};
type Takedown = {id: string; resourceName: string; territory: string; reasonCode: string; sourceReportId: string | null; effectiveDtm: string; expireDtm: string | null; revokeDtm: string | null};
type Policy = {id: string; documentName: string; versionCode: string; language: string; effectiveDtm: string; retireDtm: string | null; acceptanceCount: number};
type References = {statuses: RefItem[]; documents: RefItem[]; licenseTypes: RefItem[]; territories: RefItem[]; languages: RefItem[]; contributors: EntityRef[]; resources: EntityRef[]; reports: EntityRef[]; storageObjects: EntityRef[]};

const client = useAdminClient();
const refs = ref<References>({statuses: [], documents: [], licenseTypes: [], territories: [], languages: [], contributors: [], resources: [], reports: [], storageObjects: []});
const statuses = ref<LegalStatus[]>([]); const licenses = ref<License[]>([]); const takedowns = ref<Takedown[]>([]); const policies = ref<Policy[]>([]);
const loading = ref(true); const saving = ref(false); const error = ref(""); const q = ref("");
const statusOpen = ref(false); const licenseOpen = ref(false); const takedownOpen = ref(false); const policyOpen = ref(false);
const statusForm = reactive({resourceId: "", legalStatusCode: "", territoryCode: "WORLD", sourceType: "LEGAL_REVIEW", evidence: "{}", validUntilDtm: ""});
const licenseForm = reactive({resourceId: "", licenseTypeCode: "", rightsHolderContributorId: "", evidenceStorageObjectId: "", licenseReference: "", territoryCode: "WORLD", validFromDt: "", validUntilDt: ""});
const takedownForm = reactive({resourceId: "", sourceReportId: "", territoryCode: "WORLD", reasonCode: "", effectiveDtm: "", expireDtm: ""});
const policyForm = reactive({documentCode: "", versionCode: "", languageCode: "ru", content: "", effectiveDtm: ""});
const options = (items: RefItem[]) => items.map((item) => ({label: item.name, value: item.code}));
const entityOptions = (items: EntityRef[]) => items.map((item) => ({label: `${item.name}${item.type ? ` · ${item.type}` : ""}`, value: item.id}));
const sourceOptions = ["UPLOADER_DECLARATION", "LICENSE", "PUBLIC_DOMAIN", "RIGHTS_HOLDER", "COMPLAINT_DECISION", "LEGAL_REVIEW"].map((value) => ({label: value, value}));
const date = (value: string | null) => value ? new Date(value).toLocaleString("ru-RU") : "Без срока";

async function load() {
  loading.value = true; error.value = "";
  try {
    const search = q.value ? `?q=${encodeURIComponent(q.value)}` : "";
    const [referenceResponse, statusResponse, licenseResponse, takedownResponse, policyResponse] = await Promise.all([
      client.request<References>("/api/v1/admin/legal/references"),
      client.request<{items: LegalStatus[]}>(`/api/v1/admin/legal/resource-statuses${search}`),
      client.request<{items: License[]}>("/api/v1/admin/legal/licenses"),
      client.request<{items: Takedown[]}>("/api/v1/admin/legal/takedowns"),
      client.request<{items: Policy[]}>("/api/v1/admin/legal/policy-versions"),
    ]);
    refs.value = referenceResponse; statuses.value = statusResponse.items; licenses.value = licenseResponse.items; takedowns.value = takedownResponse.items; policies.value = policyResponse.items;
  } catch (caught: any) { error.value = caught.message || "Не удалось загрузить правовой контур"; }
  finally { loading.value = false; }
}
async function mutate(action: () => Promise<unknown>, close?: () => void) { saving.value = true; error.value = ""; try { await action(); close?.(); await load(); } catch (caught: any) { error.value = caught.message || "Операция не выполнена"; } finally { saving.value = false; } }
function openStatus() { Object.assign(statusForm, {resourceId: refs.value.resources[0]?.id || "", legalStatusCode: refs.value.statuses[0]?.code || "", territoryCode: "WORLD", sourceType: "LEGAL_REVIEW", evidence: "{}", validUntilDtm: ""}); statusOpen.value = true; }
function saveStatus() { let evidence = {}; try { evidence = JSON.parse(statusForm.evidence || "{}"); } catch { error.value = "Evidence должен быть корректным JSON"; return; } return mutate(() => client.request("/api/v1/admin/legal/resource-statuses", {method: "POST", body: JSON.stringify({...statusForm, evidence, validUntilDtm: statusForm.validUntilDtm ? new Date(statusForm.validUntilDtm).toISOString() : undefined})}), () => statusOpen.value = false); }
function openLicense() { Object.assign(licenseForm, {resourceId: refs.value.resources[0]?.id || "", licenseTypeCode: refs.value.licenseTypes[0]?.code || "", rightsHolderContributorId: "", evidenceStorageObjectId: "", licenseReference: "", territoryCode: "WORLD", validFromDt: "", validUntilDt: ""}); licenseOpen.value = true; }
function saveLicense() { return mutate(() => client.request("/api/v1/admin/legal/licenses", {method: "POST", body: JSON.stringify({resourceId: licenseForm.resourceId, licenseTypeCode: licenseForm.licenseTypeCode, rightsHolderContributorId: licenseForm.rightsHolderContributorId || undefined, evidenceStorageObjectId: licenseForm.evidenceStorageObjectId || undefined, licenseReference: licenseForm.licenseReference || undefined, territoryCodes: [licenseForm.territoryCode], validFromDt: licenseForm.validFromDt || undefined, validUntilDt: licenseForm.validUntilDt || undefined})}), () => licenseOpen.value = false); }
function openTakedown() { Object.assign(takedownForm, {resourceId: refs.value.resources[0]?.id || "", sourceReportId: "", territoryCode: "WORLD", reasonCode: "", effectiveDtm: "", expireDtm: ""}); takedownOpen.value = true; }
function saveTakedown() { return mutate(() => client.request("/api/v1/admin/legal/takedowns", {method: "POST", body: JSON.stringify({...takedownForm, sourceReportId: takedownForm.sourceReportId || undefined, effectiveDtm: takedownForm.effectiveDtm ? new Date(takedownForm.effectiveDtm).toISOString() : undefined, expireDtm: takedownForm.expireDtm ? new Date(takedownForm.expireDtm).toISOString() : undefined})}), () => takedownOpen.value = false); }
function openPolicy() { Object.assign(policyForm, {documentCode: refs.value.documents[0]?.code || "", versionCode: "", languageCode: refs.value.languages[0]?.code || "ru", content: "", effectiveDtm: ""}); policyOpen.value = true; }
function savePolicy() { return mutate(() => client.request("/api/v1/admin/legal/policy-versions", {method: "POST", body: JSON.stringify({...policyForm, effectiveDtm: new Date(policyForm.effectiveDtm).toISOString()})}), () => policyOpen.value = false); }
const revokeLicense = (item: License) => mutate(() => client.request(`/api/v1/admin/legal/licenses/${item.id}/revoke`, {method: "PATCH"}));
const revokeTakedown = (item: Takedown) => mutate(() => client.request(`/api/v1/admin/legal/takedowns/${item.id}/revoke`, {method: "PATCH"}));
onMounted(load);
</script>

<template>
  <div class="admin-page">
    <header class="admin-page__heading"><div><p class="admin-eyebrow">Legal operations</p><h1 class="text-title">Правовой контур</h1><p class="text-subtitle">Правовой статус ресурсов, лицензии, требования об удалении и версии документов платформы.</p></div><div class="admin-actions"><UiButton variant="outline" @click="openLicense">Лицензия</UiButton><UiButton variant="outline" @click="openTakedown">Takedown</UiButton><UiButton variant="primary" @click="openStatus">Изменить статус</UiButton></div></header>
    <UiCard title="Поиск"><div class="admin-toolbar"><UiInput v-model="q" label="Ресурс" placeholder="Название ресурса" @keyup.enter="load" /><UiButton variant="primary" :loading="loading" @click="load">Найти</UiButton></div></UiCard>
    <p v-if="error" class="admin-error" role="alert">{{ error }}</p><UiCard v-if="loading" title="Загрузка правового контура…" />
    <template v-else>
      <section class="mc-section"><div class="admin-section-heading"><div><p class="text-caption">Resource status</p><h2>Правовые статусы</h2></div><span class="text-caption">{{ statuses.length }}</span></div><UiEmptyState v-if="!statuses.length" title="Статусы не найдены" /><div v-else class="admin-list"><UiCard v-for="item in statuses" :key="item.id" class="admin-list-item" raw><div class="admin-list-item__main"><h3>{{ item.resourceName }}</h3><p class="mc-text-sm">{{ item.resourceType }} · {{ item.sourceType }}</p><div class="admin-meta"><span class="mc-chip">{{ item.statusName }}</span><span class="mc-chip">{{ item.territory }}</span><span v-if="item.revokeDtm" class="mc-chip">Отозван</span></div></div><p class="mc-text-sm">С {{ date(item.validFromDtm) }}<br>До {{ date(item.validUntilDtm) }}</p></UiCard></div></section>
      <section class="mc-section"><div class="admin-section-heading"><div><p class="text-caption">Licenses</p><h2>Лицензии</h2></div><span class="text-caption">{{ licenses.length }}</span></div><UiEmptyState v-if="!licenses.length" title="Лицензий пока нет" /><div v-else class="admin-list"><UiCard v-for="item in licenses" :key="item.id" class="admin-list-item" raw><div class="admin-list-item__main"><h3>{{ item.resourceName }}</h3><p class="mc-text-sm">{{ item.typeName }} · {{ item.rightsHolder || 'Правообладатель не указан' }}</p><div class="admin-meta"><span v-for="territory in item.territories" :key="territory" class="mc-chip">{{ territory }}</span><span v-if="item.revokeDtm" class="mc-chip">Отозвана</span></div></div><p class="mc-text-sm">{{ item.licenseReference || 'Без внешней ссылки' }}</p><UiButton v-if="!item.revokeDtm" size="sm" variant="ghost" @click="revokeLicense(item)">Отозвать</UiButton></UiCard></div></section>
      <section class="mc-section"><div class="admin-section-heading"><div><p class="text-caption">Takedowns</p><h2>Требования об удалении</h2></div><span class="text-caption">{{ takedowns.length }}</span></div><UiEmptyState v-if="!takedowns.length" title="Активных требований нет" /><div v-else class="admin-list"><UiCard v-for="item in takedowns" :key="item.id" class="admin-list-item" raw><div class="admin-list-item__main"><h3>{{ item.resourceName }}</h3><p class="mc-text-sm">{{ item.reasonCode }} · {{ item.territory }}</p><div class="admin-meta"><span v-if="item.sourceReportId" class="mc-chip">Есть жалоба</span><span v-if="item.revokeDtm" class="mc-chip">Отозвано</span></div></div><p class="mc-text-sm">{{ date(item.effectiveDtm) }}</p><UiButton v-if="!item.revokeDtm" size="sm" variant="ghost" @click="revokeTakedown(item)">Отозвать</UiButton></UiCard></div></section>
      <section class="mc-section"><div class="admin-section-heading"><div><p class="text-caption">Policies</p><h2>Документы платформы</h2></div><UiButton size="sm" variant="outline" @click="openPolicy">Новая версия</UiButton></div><UiEmptyState v-if="!policies.length" title="Версии ещё не опубликованы" /><div v-else class="admin-list"><UiCard v-for="item in policies" :key="item.id" class="admin-list-item" raw><div class="admin-list-item__main"><h3>{{ item.documentName }}</h3><p class="mc-text-sm">Версия {{ item.versionCode }} · {{ item.language }}</p></div><span class="mc-chip">{{ item.acceptanceCount }} принятий</span><p class="mc-text-sm">С {{ date(item.effectiveDtm) }}</p></UiCard></div></section>
    </template>

    <UiDialog v-model="statusOpen" title="Новый правовой статус" size="lg"><UiForm :loading="saving" :error="error" @submit="saveStatus"><div class="mc-form-grid"><UiSelect v-model="statusForm.resourceId" label="Ресурс" :options="entityOptions(refs.resources)" scrollable /><UiSelect v-model="statusForm.legalStatusCode" label="Статус" :options="options(refs.statuses)" /><UiSelect v-model="statusForm.territoryCode" label="Территория" :options="options(refs.territories)" /><UiSelect v-model="statusForm.sourceType" label="Источник" :options="sourceOptions" /><UiInput v-model="statusForm.validUntilDtm" label="Действует до" type="datetime-local" /></div><UiTextarea v-model="statusForm.evidence" label="Evidence JSON" rows="5" /><template #actions><UiButton variant="ghost" @click="statusOpen = false">Отмена</UiButton><UiButton type="submit" variant="primary" :loading="saving">Сохранить</UiButton></template></UiForm></UiDialog>
    <UiDialog v-model="licenseOpen" title="Новая лицензия" size="lg"><UiForm :loading="saving" :error="error" @submit="saveLicense"><div class="mc-form-grid"><UiSelect v-model="licenseForm.resourceId" label="Ресурс" :options="entityOptions(refs.resources)" scrollable /><UiSelect v-model="licenseForm.licenseTypeCode" label="Тип" :options="options(refs.licenseTypes)" /><UiSelect v-model="licenseForm.rightsHolderContributorId" label="Правообладатель" :options="[{label: 'Не указан', value: ''}, ...entityOptions(refs.contributors)]" scrollable /><UiSelect v-model="licenseForm.evidenceStorageObjectId" label="Подтверждающий файл" :options="[{label: 'Не указан', value: ''}, ...entityOptions(refs.storageObjects)]" scrollable /><UiSelect v-model="licenseForm.territoryCode" label="Территория" :options="options(refs.territories)" /><UiInput v-model="licenseForm.validFromDt" label="Действует с" type="date" /><UiInput v-model="licenseForm.validUntilDt" label="Действует до" type="date" /></div><UiInput v-model="licenseForm.licenseReference" label="Ссылка или номер договора" /><template #actions><UiButton variant="ghost" @click="licenseOpen = false">Отмена</UiButton><UiButton type="submit" variant="primary" :loading="saving">Создать</UiButton></template></UiForm></UiDialog>
    <UiDialog v-model="takedownOpen" title="Требование об удалении" size="lg"><UiForm :loading="saving" :error="error" @submit="saveTakedown"><div class="mc-form-grid"><UiSelect v-model="takedownForm.resourceId" label="Ресурс" :options="entityOptions(refs.resources)" scrollable /><UiSelect v-model="takedownForm.sourceReportId" label="Исходная жалоба" :options="[{label: 'Без жалобы', value: ''}, ...entityOptions(refs.reports)]" scrollable /><UiSelect v-model="takedownForm.territoryCode" label="Территория" :options="options(refs.territories)" /><UiInput v-model="takedownForm.reasonCode" label="Код причины" required /><UiInput v-model="takedownForm.effectiveDtm" label="Начало действия" type="datetime-local" /><UiInput v-model="takedownForm.expireDtm" label="Окончание" type="datetime-local" /></div><template #actions><UiButton variant="ghost" @click="takedownOpen = false">Отмена</UiButton><UiButton type="submit" variant="primary" :loading="saving">Создать</UiButton></template></UiForm></UiDialog>
    <UiDialog v-model="policyOpen" title="Новая версия документа"><UiForm :loading="saving" :error="error" @submit="savePolicy"><UiSelect v-model="policyForm.documentCode" label="Документ" :options="options(refs.documents)" /><UiInput v-model="policyForm.versionCode" label="Версия" required /><UiSelect v-model="policyForm.languageCode" label="Язык" :options="options(refs.languages)" /><UiInput v-model="policyForm.effectiveDtm" label="Начало действия" type="datetime-local" required /><UiTextarea v-model="policyForm.content" label="Текст документа" rows="8" required /><template #actions><UiButton variant="ghost" @click="policyOpen = false">Отмена</UiButton><UiButton type="submit" variant="primary" :loading="saving">Создать</UiButton></template></UiForm></UiDialog>
  </div>
</template>
