\set ON_ERROR_STOP on

BEGIN;

DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS video CASCADE;
DROP SCHEMA IF EXISTS music CASCADE;
DROP SCHEMA IF EXISTS library CASCADE;
DROP SCHEMA IF EXISTS legal CASCADE;
DROP SCHEMA IF EXISTS moderation CASCADE;
DROP SCHEMA IF EXISTS workflow CASCADE;
DROP SCHEMA IF EXISTS media CASCADE;
DROP SCHEMA IF EXISTS content CASCADE;
DROP SCHEMA IF EXISTS access CASCADE;
DROP SCHEMA IF EXISTS auth CASCADE;
DROP SCHEMA IF EXISTS account CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;

DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS citext;
DROP EXTENSION IF EXISTS pgcrypto;

COMMIT;
